### ISSUE TITLE
Input translated protein sequences?

### ISSUE THREAD

**Issue by charlesfoster** [huangnengCSU/compleasm#13]
Hi,

Just trying out `compleasm` for the first time. It successfully ran to completion when my input was a transcriptome assembly with nucleotide sequences. However, when I tried running `compleasm` with an input transcriptome with translated protein sequences the analysis failed. Similar to https://github.com/huangnengCSU/compleasm/issues/12, I got the following:

```
Traceback (most recent call last):
  File "/home/cfos/miniconda3/envs/compleasm/bin/compleasm", line 10, in <module>
    sys.exit(main())
  File "/home/cfos/miniconda3/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 2534, in main
    args.func(args)
  File "/home/cfos/miniconda3/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 2376, in analyze
    ar.Run()
  File "/home/cfos/miniconda3/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 1158, in Run
    self.Run_busco_mode()
  File "/home/cfos/miniconda3/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 1234, in Run_busco_mode
    filtered_species = records_df["Target_species"].unique()
  File "/home/cfos/miniconda3/envs/compleasm/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/cfos/miniconda3/envs/compleasm/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Target_species'
```

Is there a 'proteins' mode like in BUSCO (`-m proteins`)? Or should `compleasm` always use a nucelotide input?

Thanks

**Comment by huangnengCSU** [comment]
Hi @charlesfoster ,

There is a branch v0.2.3 that supports the protein mode. But we did not test it with enough data. You just clone it and run with the same environment as installed compleasm.

**Comment by charlesfoster** [comment]
Great, thanks for the quick reply.
