### ISSUE TITLE
Error - download submodule

### ISSUE THREAD

**Issue by rlibouba** [huangnengCSU/compleasm#20]
Hello, 

I have a problem when I want to use the download submodule. 

I have installed the latest version. Here is the error I got:

`md5 hash is incorrect: 8f6c62320cd30f8017af530cbb099536 while 8f6c62320cd30f8017af530cbb099536  file_versions.tsv expected
deleting corrupted file mb_downloads/file_versions.tsv
Unable to download necessary files
Traceback (most recent call last):
  File "/home/rlibouba/.conda/envs/mamba/envs/comp/bin/compleasm", line 10, in <module>
    sys.exit(main())
  File "/home/rlibouba/.conda/envs/mamba/envs/comp/lib/python3.7/site-packages/compleasm.py", line 2711, in main
    args.func(args)
  File "/home/rlibouba/.conda/envs/mamba/envs/comp/lib/python3.7/site-packages/compleasm.py", line 2473, in download
    downloader = Downloader(args.library_path)
  File "/home/rlibouba/.conda/envs/mamba/envs/comp/lib/python3.7/site-packages/compleasm.py", line 85, in __init__
    self.lineage_description, self.placement_description = self.download_file_version_document()
  File "/home/rlibouba/.conda/envs/mamba/envs/comp/lib/python3.7/site-packages/compleasm.py", line 138, in download_file_version_document
    expected_file_version_hash)
  File "/home/rlibouba/.conda/envs/mamba/envs/comp/lib/python3.7/site-packages/compleasm.py", line 105, in download_single_file
    raise Error("Unable to download necessary files")
compleasm.Error: Unable to download necessary files`

Do you have any idea what the problem is? 
Thank you for your help.
Have a nice day!

**Comment by huangnengCSU** [comment]
Hi,
May I ask which lineage would you like to download?

**Comment by rlibouba** [comment]
I tested with mollusca, eukaryota and primates. I got the same error. Yesterday, I had no trouble downloading them.

**Comment by huangnengCSU** [comment]
Some BUSCO file formats have changed. I have solved the problem. But currently you have to clone the repo and run it again. Before downloading, remember to delete the destination folder to store the downloaded lineage files. (default is mb_downloads). I will update bioconda later.

**Comment by Pav-mis** [comment]
Hi,

I see that the comment has been closed, and you've created a new release. I was wondering if this release will be available on dockerhub? The current version of the container does not work.

**Comment by huangnengCSU** [comment]
Hi @Pav-mis,

I have just updated the dockerhub ```huangnengcsu/compleasm:v0.2.5```
