### ISSUE TITLE
compleasm download error

### ISSUE THREAD

**Issue by ChuanzhengWei** [huangnengCSU/compleasm#25]
Hello, I encountered some problems while using the download module. I'm not sure how they arose. My error message:
```
Traceback (most recent call last):
  File "/opt/conda/envs/compleasm/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/conda/envs/compleasm/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/envs/compleasm/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/compleasm/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/compleasm/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/conda/envs/compleasm/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/opt/conda/envs/compleasm/lib/python3.7/http/client.py", line 1443, in connect
    super().connect()
  File "/opt/conda/envs/compleasm/lib/python3.7/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/conda/envs/compleasm/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/opt/conda/envs/compleasm/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/compleasm/bin/compleasm", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 2737, in main
    args.func(args)
  File "/opt/conda/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 2497, in download
    downloader = Downloader(args.library_path)
  File "/opt/conda/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 85, in __init__
    self.lineage_description, self.placement_description = self.download_file_version_document()
  File "/opt/conda/envs/compleasm/lib/python3.7/site-packages/compleasm.py", line 127, in download_file_version_document
    urllib.request.urlretrieve(hash_url, hash_download_path)
  File "/opt/conda/envs/compleasm/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/opt/conda/envs/compleasm/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/envs/compleasm/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/envs/compleasm/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/conda/envs/compleasm/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/conda/envs/compleasm/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/conda/envs/compleasm/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>

```
Here are my commands:
`singularity exec compleasm.sif compleasm download eukaryota`
My version is v2.0.5.

Regards!

**Comment by ChuanzhengWei** [comment]
I'm not sure why, but I just ran the same command and it worked this time.
